authority = "cpan:PINE"
authors = ["Pine Mizune"]
badges = ["travis", "appveyor", "codecov"]
license = "mit"
markdown_maker = "Pod::Markdown::Github"
module_maker="ModuleBuildTiny"
name = "Mac-OSVersion-Lite"

